// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdUkLrLXkqajDPQSGJIpuLbfut9KwnFNM',
    appId: '1:450155696339:web:aedf7a2f29905f72b10426',
    messagingSenderId: '450155696339',
    projectId: 'kaipromptv1',
    authDomain: 'kaipromptv1.firebaseapp.com',
    storageBucket: 'kaipromptv1.appspot.com',
    measurementId: 'G-PWPLTK974Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG5Cx6TfAOTYmKu3embv1z703J-xjxuGY',
    appId: '1:450155696339:android:26ef44f8aa1db492b10426',
    messagingSenderId: '450155696339',
    projectId: 'kaipromptv1',
    storageBucket: 'kaipromptv1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz6TOz2ecfOYubFU9mMO-HE5mfd7ndLHc',
    appId: '1:450155696339:ios:e9554d43ff4e7b61b10426',
    messagingSenderId: '450155696339',
    projectId: 'kaipromptv1',
    storageBucket: 'kaipromptv1.appspot.com',
    iosClientId: '450155696339-aii47cgn3dklr3ma02rek2harb4e0qfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.kaiprompt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz6TOz2ecfOYubFU9mMO-HE5mfd7ndLHc',
    appId: '1:450155696339:ios:28fe46b3caff2b95b10426',
    messagingSenderId: '450155696339',
    projectId: 'kaipromptv1',
    storageBucket: 'kaipromptv1.appspot.com',
    iosClientId: '450155696339-s9vnj75in3q3aiir8emu3mv6qshbakhv.apps.googleusercontent.com',
    iosBundleId: 'com.example.kaiprompt.RunnerTests',
  );
}
